# Generated by Django 4.2.3 on 2023-07-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='cretaed',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='cretaed',
            new_name='created',
        ),
    ]
